spring:
  application:
    name: LR4_Logger
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1234
    url: jdbc:postgresql://localhost:5432/library_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  artemis:
    user: admin
    password: admin
  jms:
    pub-sub-domain: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ttestov710@gmail.com
    password: xnaazaerlcozpgcz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  audit:
    topic: audit.queue