version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: esa
    ports:
      - "5432:5432"
